import { OnlineUserProvider } from "@/constants/OnlineUserProvider";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <OnlineUserProvider>{children}</OnlineUserProvider>
        <Toaster />
      </body>
    </html>
  );
}
