import "./globals.css"
import { Toaster } from "sonner"

import { AuthProvider } from "@/contexts/auth-context";
import { PermissionProvider } from "@/contexts/permission-context";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <PermissionProvider>
          {children}
          <Toaster /> 
          </PermissionProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
